# PostgreSQL configuration.
# Ensure the "pg" gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_PUBLIC_URL'] %>

development:
  <<: *default

production:
  <<: *default
  pool: 10
  timeout: 5000
